# .github/workflows/build.yml
name: Build CustomAuth

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file CustomAuth-Core/pom.xml
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CustomAuth
        path: target/CustomAuth-*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: CustomAuth
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: CustomAuth-*.jar
