# .github/workflows/release.yml
name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '1.0.0'
        required: true
      prerelease:
        description: 'Is this a prerelease?'
        type: boolean
        default: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Update version in pom.xml
      run: |
        mvn versions:set -DnewVersion=${{ github.event.inputs.version }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump version to ${{ github.event.inputs.version }}"
        git tag v${{ github.event.inputs.version }}
    
    - name: Build with Maven
      run: mvn -B package --file CustomAuth-Core/pom.xml
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        draft: false
        prerelease: ${{ github.event.inputs.prerelease }}
        generate_release_notes: true
        files: target/CustomAuth-*.jar
